networks:
  web1:

services:

  backend:
    build:
      context: ./back
    ports:
      - "2288:2288"
    networks:
      - web1


  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "5830:80"
    depends_on:
      - backend
    networks:
      - web1
